# Generated by Django 5.2.1 on 2026-04-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_chatgroup_admins_only'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatgroup',
            options={'ordering': ['name']},
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chatapp_mes_chat_id_50cef6_idx',
            old_name='chatapp_mes_chat_id_6ebbe1_idx',
        ),
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
