# Generated by Django 5.2.1 on 2026-04-06 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0007_add_phone_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('meet_link', models.CharField(max_length=500)),
                ('scheduled_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='chatapp.employee')),
                ('invitees', models.ManyToManyField(blank=True, related_name='invited_meetings', to='chatapp.employee')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
    ]
