# Generated by Django 5.2.1 on 2026-04-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0010_add_is_read_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
