from django.urls import path

from .views import (
    AllMessagesView,
    BookmarkDetailView,
    BookmarkListView,
    EmployeeDetailView,
    EmployeePermissionView,
    EmployeesView,
    ForgotPasswordView,
    GroupAdminsOnlyView,
    GroupMemberView,
    GroupDetailView,
    GroupListView,
    HealthView,
    LoginView,
    MeetingView,
    MessageDetailView,
    MessageLinkView,
    MessageListView,
    MessageUploadView,
    NotificationDetailView,
    NotificationListView,
    ProfileView,
    ResetPasswordView,
    VerifyOtpView,
)


urlpatterns = [
    path("auth/login", LoginView.as_view()),
    path("auth/profile", ProfileView.as_view()),
    path("auth/forgot-password", ForgotPasswordView.as_view()),
    path("auth/verify-otp", VerifyOtpView.as_view()),
    path("auth/reset-password", ResetPasswordView.as_view()),
    path("auth/employees", EmployeesView.as_view()),
    path("auth/employees/<int:employee_id>", EmployeeDetailView.as_view()),
    path("auth/employees/<int:employee_id>/permissions", EmployeePermissionView.as_view()),
    path("auth/all-messages", AllMessagesView.as_view()),
    path("meetings", MeetingView.as_view()),
    path("meetings/<int:meeting_id>", MeetingView.as_view()),
    path("groups", GroupListView.as_view()),
    path("groups/<int:group_id>", GroupDetailView.as_view()),
    path("groups/<int:group_id>/admins-only", GroupAdminsOnlyView.as_view()),
    path("groups/<int:group_id>/members/<int:employee_id>", GroupMemberView.as_view()),
    path("messages/upload", MessageUploadView.as_view()),
    path("messages/link", MessageLinkView.as_view()),
    path("messages/<str:chat_id>", MessageListView.as_view()),
    path("messages", MessageDetailView.as_view()),
    path("notifications", NotificationListView.as_view()),
    path("notifications/<int:notif_id>", NotificationDetailView.as_view()),
    path("bookmarks", BookmarkListView.as_view()),
    path("bookmarks/<int:bookmark_id>", BookmarkDetailView.as_view()),
    path("health", HealthView.as_view()),
]
